server:
  port: 8882

spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
      #uri: http://127.0.0.1:8888/
      discovery:
        enabled: true
        service-id: config-server
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka/

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh


